const INIT_SEEDS_COUNT = 5;
const HOLE_NUMBERS = INIT_SEEDS_COUNT*2;


const config = {
    INIT_SEEDS_COUNT: INIT_SEEDS_COUNT,
    HOLE_NUMBERS: HOLE_NUMBERS,
    MIN_INDEX_LOWER: INIT_SEEDS_COUNT,
    MAX_INDEX_LOWER: HOLE_NUMBERS - 1,
    MIN_INDEX_UPPER: 0,
    MAX_INDEX_UPPER: INIT_SEEDS_COUNT - 1,
}

export default config;