<<<<<<< HEAD
// gamePhaseConfig

=======
>>>>>>> d3ca549e6e029639aa9d28bc0c21879e873dc215
const gamePhaseConfig = {
    STARTING_PHASE : 'STARTING_PHASE',
    SIMULTANEOUS_SELECT : 'SIMULTANEOUS_SELECT',
    SIMULTANEOUS_SELECT_UPPER : 'SIMULTANEOUS_SELECT_UPPER',
    SIMULTANEOUS_SELECT_LOWER : 'SIMULTANEOUS_SELECT_LOWER',
    PASS_TO_TURN_BASED : 'PASS_TO_TURN_BASED',
<<<<<<< HEAD
    TURN_BASED_SELECT : 'TURN_BASED_SELECT',
    TURN_BASED_SOWING : 'TURN_BASED_SOWING'
=======
    TURN_BASED_SOWING : 'TURN_BASED_SOWING',
    TURN_BASED_SELECT : 'TURN_BASED_SELECT',
>>>>>>> d3ca549e6e029639aa9d28bc0c21879e873dc215
}

export default gamePhaseConfig;